name: Replay_ID_2018
channels:
- conda-forge
- defaults
- edeno
dependencies:
- "python >= 3.6"
- loren_frank_data_processing
- ripple_detection
- replay_classification
- replay_identification
- jupyter
- setuptools
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- netcdf4
