name: Replay_ID_2018
channels:
- conda-forge
- defaults
- edeno
dependencies:
- "python >= 3.6"
- numpy
- scipy
- pandas
- xarray
- seaborn
- joblib
- loren_frank_data_processing
- ripple_detection
- spectral_connectivity
- replay_identification
- replay_classification
- replay_trajectory_classification
- jupyter
- setuptools
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- netcdf4
